### ISSUE TITLE
Permanent location for CSV?

### ISSUE THREAD

**Issue by riceissa** [ackerleytng/logaze#11]
Is there a permanent URL from which to download the CSV? Currently the URLs look like https://jsonblob.com/api/jsonBlob/381d4455-63af-11ea-ad21-453934360a11 which I suspect are just for the current version and will become out of date when the Outlet site is scraped again.

I know I could use a headless browser or something along those lines to load the page and click the "csv" link, but I'd like to avoid doing that if possible.

**Comment by ackerleytng** [comment]
The jsonblob address is always the latest state of the data, when the outlet site is scraped, it will write to that same jsonblob address! See https://github.com/ackerleytng/logaze/blob/master/src/data.js#L4.

Unfortunately the csv is generated client-side, but the data is basically just transformed from the jsonblob at the address you found. Hope json works for you too!

Is there some particular filtering that you wanted to do that logaze doesn't support?

**Comment by riceissa** [comment]
Oh I see, thanks! Yes, JSON works great for me.

Logaze does support almost everything I want (the only thing that would be nice is to have inequality checking like the "greater than or equals" comparison in memory, not just price). But the bigger problem with the frontend is that I don't know how to save the specific filters I've set; it seems that every time I reload the page I have to put in my filters all over again.

**Comment by ackerleytng** [comment]
Ah ok. If I manage to find some time I'll implement some way to store the filters :)

Thanks for the suggestion!
