### ISSUE TITLE
Implement some way of saving table filters

### ISSUE THREAD

**Issue by ackerleytng** [ackerleytng/logaze#12]

**Comment by danieljin** [comment]
https://www.ag-grid.com/javascript-data-grid/filter-api/ Looks like you should be able to save filters using this.

gridOptions.api.getFilterModel(); 
JSON stringify it
then store in localStorage

**Comment by ackerleytng** [comment]
Thanks for the tip! I was just looking into this yesterday.

This has been implemented! It should now save sort/filter settings whenever the user changes them, and load the previous settings whenever you refresh.

**Comment by danieljin** [comment]
works great! thanks for implementing so quickly.

**Comment by github-account1111** [comment]
I am confused. Not seeing a save button anywhere. Can't seem to bookmark the results either because the address stays the same.

**Comment by ackerleytng** [comment]
There's no save button, as long as you change the sorting/filtering configuration it should get saved, and it should reload the old configuration when you next visit logaze.

To reset the grid to defaults, use the `reset grid` button at the top right.
