### ISSUE TITLE
Buy link points to wrong URL address.

### ISSUE THREAD

**Issue by TurdPooCharger** [ackerleytng/logaze#14]
Example when trying to buy this P1 Gen 3.

Old Address
https://www.lenovo.com/us/en/outletus/laptops/thinkpad/thinkpad-p/ThinkPad-P1-Gen-3/p/20TJX01300

New Address
https://www.lenovo.com/us/outletus/en/p/laptops/thinkpad/thinkpadp/thinkpad-p1-gen-3/20tjx01300

**Comment by ackerleytng** [comment]
Will look into this. Thanks for letting me know!

**Comment by ackerleytng** [comment]
Updated it! Lenovo's website changed, so the scraping broke. Updated the scraper to use their new openapi API
