### ISSUE TITLE
It has been stuck showing the same 341 listings for at least a week now. Even after updating.

### ISSUE THREAD

**Issue by solomo11** [ackerleytng/logaze#15]
It looks like it has stopped actually pulling new records. It has shown the exact same 341 listings, most of which are now no longer available for at least the last week, if not longer.

**Comment by ackerleytng** [comment]
Thanks for letting me know! I'll look into it.

**Comment by ackerleytng** [comment]
Fixed with https://github.com/ackerleytng/logaze-scraper/commit/85564d9ba5c8a25204468c281ec8bdbe83e69c06 !
