### ISSUE TITLE
Please implement % discount

### ISSUE THREAD

**Issue by chuncl** [ackerleytng/logaze#16]
thanks for the good work, there is original price and current price column. it would be helpful to add % discount column

**Comment by ackerleytng** [comment]
+ Extracting percentage savings in https://github.com/ackerleytng/logaze-scraper/commit/ec4dd504799e2d20b3c845f0b39f8436b5f647ec
+ Displaying percentage savings in https://github.com/ackerleytng/logaze/commit/55941084c705a9e2b6943fc847ed5a4ae513735a
