### ISSUE TITLE
"Price" captures "Est Value" after latest update- wrong price scraped/displayed

### ISSUE THREAD

**Issue by Vertig0000** [ackerleytng/logaze#20]
After a recent update (~24-48 hours ago) on the Outlet site, the tracker seems to be picking up the "Est Value" (full price) instead of the "Outlet Price" (actual price) from all the pages.

Ex:

https://www.lenovo.com/us/outletus/en/p/laptops/lenovo/lenovo-edu-chromebooks/ideapad-flex-3-cb-11igl05/82bb0009us
Est Value: $279.99
Lenovo Outlet Price: $254.79

Tracker chooses the $279.99 vaue as the "Price" to display.

_(Thanks for a great tool!)_

**Comment by ackerleytng** [comment]
Thanks for letting me know! I wonder if this is a bug on their side - I'm surprised that on the main page: https://www.lenovo.com/us/outletus/en/laptops/ the non-discounted prices are listed instead of the discounted ones. 

If this doesn't get fixed on their side I'll look into it again.

**Comment by Vertig0000** [comment]
A bug would not surprise me, given the overall wonkiness of their site... Thanks again.

**Comment by ackerleytng** [comment]
I believe this has been fixed on their side!
