### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by chuncl** [ackerleytng/logaze#22]
It has been "320 laptops" for many days, many items are out of stock now. rescrape doesn't update properly.

**Comment by ackerleytng** [comment]
Acknowledged, will look into it!

**Comment by ackerleytng** [comment]
I think the host I was using was being throttled, I've switched to another host, hopefully that will be better! Keeping this open for a bit.

**Comment by ackerleytng** [comment]
The new hosting at koyeb.com is working fine :)
