### ISSUE TITLE
logaze rescrape doesn't work

### ISSUE THREAD

**Issue by chuncl** [ackerleytng/logaze#24]
logaze rescrape doesn't work. it has been "404 laptops found" for a few days, even lenovo outlet's laptop quantity changes. please resolve. thanks

**Comment by ackerleytng** [comment]
Thanks for reporting this. I acknowledge the issue, I'll get to it as soon as I can

**Comment by ackerleytng** [comment]
I believe this has been fixed, please reopen if it doesn't work for you!
