### ISSUE TITLE
not working, always show "40 laptops found,"

### ISSUE THREAD

**Issue by chuncl** [ackerleytng/logaze#26]
it is not working, always show "40 laptops found," please have a look

thanks

**Comment by ackerleytng** [comment]
I think it might be a bug on Lenovo's side, it seems okay now? I'll leave this open for a while.

**Comment by ackerleytng** [comment]
I think I found the bug. When scraping for products takes too long, the async part that finds details for each part clears out the request list too quickly and prematurely ends the scraping.

This bug should be fixed now.

**Comment by chuncl** [comment]
Thank you!
