### ISSUE TITLE
No legion's gen 8 Laptops

### ISSUE THREAD

**Issue by nasserdiallo** [ackerleytng/logaze#28]
Hello great job with this tool.
Please why are there no legion's gen 8 laptops (2023) ?

**Comment by ackerleytng** [comment]
Logaze is just a different interface for the Lenovo outlet.

I just checked https://www.lenovo.com/us/outletus/en/search?fq=&text=Legion&rows=20&sort=relevance&fsid=1, Lenovo doesn't seem to have any legion gen 8 laptops for sale now at their outlet. If it's not available there, logaze won't show it! :)
