### ISSUE TITLE
Some out of stock items are showing up on the tracker

### ISSUE THREAD

**Issue by henryjin3** [ackerleytng/logaze#3]
Specifically, it seems that there are models which show up on the outlet (the "view current models" tab is still there) but when you scroll down, the add to cart button is greyed out and there is an Out of Stock message.

Is it possible for the scraper to key off of one of these elements as well and ignore these listings? For example, this [link](https://www.lenovo.com/us/en/outletus/laptops/thinkpad/thinkpad-x-series/X1-Carbon-Gen-7/p/20QDCTR1WW-PF14Z97B) has the following element:

` <span class="rci-msg" style="color: #9c3022; font-weight: bold;">				Out of Stock</span>`

And the add to cart button has the disabled attribute.

**Comment by ackerleytng** [comment]
Thanks for letting me know! I'm looking into it.

**Comment by ackerleytng** [comment]
I've added code to filter out Out of Stock items!

Please reopen this issue if they still appear.
