### ISSUE TITLE
Columns collapse on repeat visits

### ISSUE THREAD

**Issue by github-account1111** [ackerleytng/logaze#31]
After I applied the desired filters, left the site and revisited the next day, the first 9 columns were collapsed.

- I was able to reproduce after clearing browsing data.
- As far as I can tell, if I rearrange the columns, it's still the first 9 that get collapsed regardless of which ones are first.
- I'm using Safari on macOS.

<img width="1470" alt="image" src="https://github.com/ackerleytng/logaze/assets/5728319/301d923a-271d-413a-864f-2238eaafe986">

**Comment by ackerleytng** [comment]
Thanks for reporting this, and thanks for the screenshot! I wasn't able to reproduce that on Chrome, and I don't have easy access to Safari.

May I know what filters you used?

The filters are also saved in LocalStorage, so if you could paste that here, it would be great!

Use the shortcut `Option + ⌘ + C` to open safari's developer console, then in the console, type `copy(localStorage)`, and paste that here.

Does the `reset grid` button (top right of logaze) clear the grid and reset everything for you?

**Comment by ackerleytng** [comment]
I've also updated the dependencies, including the library used for the grid, so perhaps that would fix the issue.

**Comment by tomkimberlin** [comment]
Still an issue for me on iOS Safari and Firefox.

**Comment by ackerleytng** [comment]
Removed column autosizing, let me know if that helps!

**Comment by tomkimberlin** [comment]
> Removed column autosizing, let me know if that helps!

Seems to be resolved now. Thanks!

**Comment by github-account1111** [comment]
Seems fixed on my end as well. Sorry for the delay. I've since cleared browsing data a few more times, and the issue hasn't returned.

> May I know what filters you used?

I used the `Contains` and `Does not contain` filters in the Memory and Processor columns.

**Comment by ackerleytng** [comment]
Thanks for confirming! This is not quite a fix since I removed the auto sizing feature, but I think we're good without that feature.
